name: Setup Gradle
description: Sets Gradle up to run properly

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: microsoft
    - run: chmod +x ./gradlew
      shell: bash
    - uses: gradle/wrapper-validation-action@v1.0.4