build:
  maxIssues: 0
  excludeCorrectable: false
  weights:
  # complexity: 2
  # LongParameterList: 1
  # style: 1
  # comments: 1

config:
  validation: true
  warningsAsErrors: false
  checkExhaustiveness: false
  # when writing own rules with new properties, exclude the property path e.g.: 'my_rule_set,.*>.*>[my_property]'
  excludes: ''

processors:
  active: true
  exclude:
    - 'DetektProgressListener'
  # - 'KtFileCountProcessor'
  # - 'PackageCountProcessor'
  # - 'ClassCountProcessor'
  # - 'FunctionCountProcessor'
  # - 'PropertyCountProcessor'
  # - 'ProjectComplexityProcessor'
  # - 'ProjectCognitiveComplexityProcessor'
  # - 'ProjectLLOCProcessor'
  # - 'ProjectCLOCProcessor'
  # - 'ProjectLOCProcessor'
  # - 'ProjectSLOCProcessor'
  # - 'LicenseHeaderLoaderExtension'

console-reports:
  active: true
  exclude:
    - 'ProjectStatisticsReport'
    - 'ComplexityReport'
    - 'NotificationReport'
    - 'FindingsReport'
    - 'FileBasedFindingsReport'
  #  - 'LiteFindingsReport'

output-reports:
  active: true
  exclude:
  # - 'TxtOutputReport'
  # - 'XmlOutputReport'
  # - 'HtmlOutputReport'
  # - 'MdOutputReport'

complexity:
  active: true
  LongMethod:
    threshold: 200
  TooManyFunctions:
    thresholdInClasses: 35
    ignorePrivate: true
    ignoreOverridden: true
  CyclomaticComplexMethod:
    ignoreSingleWhenExpression: true
    ignoreSimpleWhenEntries: true

style:
  active: true
  ReturnCount:
    max: 4
    excludeGuardClauses: true
  NewLineAtEndOfFile:
    active: false
  WildcardImport:
    active: false
  ForbiddenComment:
    active: false
  LoopWithTooManyJumpStatements:
    maxJumpCount: 3
  UnusedPrivateMember: # TODO: maybe just lower severity to warning or something?
    active: false

formatting:
  active: true
  FinalNewline:
    active: false
  NoWildcardImports:
    active: false
  Filename:
    active: false