name: Check style via Diktat

on:
  pull_request:
    branches:
      - master
  push:

jobs:
  run_diktat:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: ./.github/actions/setup_gradle
      - name: Run diktat
        uses: gradle/gradle-build-action@v2.2.0
        with:
          # --continue so we can aggregate all errors
          arguments: diktatCheck --continue
      - name: Upload SARIF Report
        uses: github/codeql-action/upload-sarif@v2
        if: ${{ always() }}
        with:
          sarif_file: ${{ github.workspace }}